### ISSUE TITLE
ppv is incorrectly calculated when sensitivity is NA

### ISSUE THREAD

**Issue by alejandroschuler** [tidymodels/yardstick#101]
Consider the following example:

```
library(yardstick)
library(tidyverse)

df = tibble(
    truth = FALSE, 
    est = TRUE
) %>% mutate_all(factor, levels=c("TRUE", "FALSE"))

df
# A tibble: 1 x 2
  truth est  
  <fct> <fct>
1 FALSE TRUE 

df %>% ppv(truth, est)
# A tibble: 1 x 3
  .metric .estimator .estimate
  <chr>   <chr>          <dbl>
1 ppv     binary            NA
```

The ppv comes out as `NA` when it should clearly be 0/1 = 0. The problem is that a formula involving specificity and sensitivity is used in the code to calculate ppv. In this example, the sensitivity is `NA`, which corrupts the calculation. 

The formula that is used is useful in settings with biased case-control sampling, but otherwise should not be used. If no prevalence is provided, the calculation should be something like `mean(truth[est=="TRUE"]=="TRUE")`.

**Comment by topepo** [comment]
> The ppv comes out as NA when it should clearly be 0/1 = 0. 

It wouldn't be horrid to have PPV = 0 iff sens = 0 (and NPV = 0 iff spec = 0). 

> If no prevalence is provided, the calculation should be something like `mean(truth[est=="TRUE"]=="TRUE").`

I disagree here. Prevalence is used in every term in those formulas. We should require a value for prevalence no matter what. You can make it informative if you don't have/know a value using `prevalence = 0.50`.

**Comment by alejandroschuler** [comment]
> It wouldn't be horrid to have PPV = 0 iff sens = 0 (and NPV = 0 iff spec = 0).

Do you mean iff sens == NA? 

> I disagree here. Prevalence is used in every term in those formulas. We should require a value for prevalence no matter what. You can make it informative if you don't have/know a value using prevalence = 0.50.

I'm not sure I understand what you mean. If prevalence is not given by the user, the only assumption that can be made is that the data are a fair sample so the prevalence should be estimated as (TP+FN) / (TP+FN+FP+TN).  However, you don't need to calculate that explicitly because the natural estimator for ppv under random sampling, TP / (TP + FP), already takes that into account. Am I missing something?

I'm ultimately agnostic about how this is resolved, but I'd obviously like to have correct values be produced.

**Comment by topepo** [comment]
> Do you mean iff sens == NA?

No, when sens = 0. Otherwise, missing values propagate missing values (`PPV = NA/(NA+X)`). If it is zero, as you point out, it is `0/X`. 

> If prevalence is not given by the user

...then we should either 

1. compute it from the data and use that value (i.e. empirical Bayes) or 

2. we have no idea what it is and shouldn't report a value. 

> the only assumption that can be made is that the data are a fair sample

> the natural estimator for ppv under random sampling

These makes a whole host of assumptions that can often be very wrong. If you have a a moderate to large class imbalance, which is not  uncommon, then that estimator is very bad. I'd rather do nothing than the alternatives. 

Why would someone want an unconditional measure like the PPV if they are not willing to compute or specify a prevalence?

**Comment by alejandroschuler** [comment]
I guess I'm confused because the code already does what I suggest re: assuming a random sample if no prevalence is provided: https://github.com/tidymodels/yardstick/blob/089cfb9be545b9255fe2656d27bcba3f1adc4c7f/R/class-ppv.R#L139

If you're already doing that, then it makes sense to just use the random sample estimator instead of computing prevalence and feeding it into the known-prevalence estimator. Seems simpler and it would address my issue. 

So it seems that the two rational alternatives are:
1. The user should be forced to provide a prevalence. If they do not, there is an error. Users with random samples must go through the extra trouble of estimating prevalence themselves. Users accept that PPV cannot be calculated unless sensitivity and specificity can be calculated. 
2. The sample is assumed random unless a prevalence is provided (this is what the current code does, albeit with an edge case failure). The code is corrected so that PPV can be calculated in all cases in which it is theoretically possible to do so. This includes cases where the sample is random, but sensitivity cannot be calculated (as in my example).

I like 2 better, but it is absolutely true that computing PPV without prevalence known a-priori is not possible under biased sampling. Users may not be aware of this. Perhaps a warning should be produced if a random sample is being assumed (i.e. prevalence is estimated from the data) under option 2?

**Comment by topepo** [comment]
Not to be argumentative but:

> assuming a random sample if no prevalence is provided:

It's not a _random sample_; it is the _whole data set_. This is a pretty standard approach. If feel like we are using two different sets of terminology.  

We can estimate PPV and NPV to be zero when the statistic in the numerator is zero. I don't think that we should make any other changes apart from documenting it more in the help file about this.

**Comment by alejandroschuler** [comment]
No worries- and yes, I'm using the standard statistical terminology in which the entire dataset is considered to be a random sample from a larger population or data-generating process. If the data are a true random sample from the data generating process, then it's possible to estimate prevalence as you do in the code. If you have upsampling from particular subpopulations (i.e. upsampled minority classes), clearly the prevalence can't be estimated from those data. I presume this is what you were referring when you said that the TP / (TP + FP) estimator requires additional assumptions.

I'm not sure if doing what you suggest would solve my problem or if it would introduce additional problems. But maybe I'm not coming across right. To reset- do you agree that in the example I showed, the PPV should be 0 and not NA? Even if we specify `prevalence=0`?

**Comment by DavisVaughan** [comment]
We've had a warning about this case for a little while now (since #118), but it was actually incorrectly throwing a recall specific warning rather than a sens one (the metrics are the same, just different names). #210 fixes the warning.

Since the warning is a pretty good indicator that something odd is going on, and it explains exactly what is happening, I'm going to close this one.

``` r
library(yardstick)
library(tidyverse)

df = tibble(
  truth = FALSE, 
  est = TRUE
) %>% 
  mutate_all(factor, levels=c("TRUE", "FALSE"))

df
#> # A tibble: 1 x 2
#>   truth est  
#>   <fct> <fct>
#> 1 FALSE TRUE

ppv(df, truth, est)
#> Warning: While computing binary `sens()`, no true events were detected (i.e. `true_positive + false_negative = 0`). 
#> Sensitivity is undefined in this case, and `NA` will be returned.
#> Note that 1 predicted event(s) actually occured for the problematic event level, 'TRUE'.
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 ppv     binary            NA
```

<sup>Created on 2021-03-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
