### ISSUE TITLE
metrics 

### ISSUE THREAD

**Issue by spedygiorgio** [tidymodels/yardstick#11]
Hi could it be possible to add two useful metrics: normalizedGini and poissonLogLoss?

The code for normalized gini can be found in MLmetrics, regarding the Poisson LogLoss a possible example is this one:

`
#include <Rcpp.h>
#include <math.h>
using namespace Rcpp;

// original R function
// function (y_pred, y_true) 
// {
//   eps <- 1e-15
//   y_pred <- pmax(y_pred, eps)
//   Poisson_LogLoss <- mean(log(gamma(y_true + 1)) + y_pred - 
//     log(y_pred) * y_true)
//   return(Poisson_LogLoss)
// }

// [[Rcpp::export]]
double poissonLogLoss(NumericVector predicted, NumericVector actual) {
  NumericVector temp, y_pred_new;
  double out; 
  const double eps=1e-15;
  
  y_pred_new=pmax(predicted,eps);
  temp = log(gamma(actual + 1)) + y_pred_new - log(y_pred_new)*actual;
  out=mean(temp); // using sugar implementation
  return out;
}
`

**Comment by topepo** [comment]
Sure. The fasted way to get things in there right now is to do a PR.

**Comment by topepo** [comment]
Couldn't we get via deviance? 

```r
> poisson()$dev.resids
function (y, mu, wt) 
{
    r <- mu * wt
    p <- which(y > 0)
    r[p] <- (wt * (y * log(y/mu) - (y - mu)))[p]
    2 * r
}
```

**Comment by jaredlander** [comment]
Deviance seems to be common and would work for poisson regression. But how would `metrics()` determine the `truth` column is count data? I remember `{mi}` would guess based on the column being stored as an integer and having low numbers, but those heuristics will fail a lot.

**Comment by DavisVaughan** [comment]
Splitting this into two issues
