### ISSUE TITLE
pROC::roc and yardstick::roc_auc have opposite results when specifying same direction

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/yardstick#131]
Hi,

It seems like the `direction` argument when passed directly to `pROC::roc()` operates in the opposite way as when it is passed in a list of options via `options` to `yardstick::roc_auc()`. I have simulated some data below which explicitly have made the "cases" group have a higher predictort value than the "controls" group.

According to the help documentation for `pROC::roc()`, here is the descrition of how to use the direction argument:

> in which direction to make the comparison? “auto” (default): automatically define in which group the median is higher and take the direction accordingly. “>”: if the predictor values for the control group are higher than the values of the case group (controls > t >= cases). “<”: if the predictor values for the control group are lower or equal than the values of the case group (controls < t <= cases). You should set this explicity to “>” or “<” whenever you are resampling or randomizing the data, otherwise the curves will be biased towards higher AUC values.

Based on this description, I would set `direction = "<"`, since controls have lower predictor values. When I do this in `pROC::roc()` directly, I get the correct AUC and it agrees with the "auto" method. However, when passed as an option to `yardstick::roc_auc()` I get the complementary AUC. When flipping the direction to `">"` for `roc_auc()` it now agrees with `"<"` for `roc()`.

I can't tell if I am losing my mind or if this an actual bug.

``` r
library(dplyr)

set.seed(1234)
data <-
  tibble(
    bi = rep(c(0L, 1L), each = 20),
    pr = c(rnorm(20, -1), rnorm(20, 1))
  ) %>% 
  mutate(bi = factor(bi, levels = c(0, 1)))

data %>% group_by(bi) %>% summarise(median(pr))
#> # A tibble: 2 x 2
#>   bi    `median(pr)`
#>   <fct>        <dbl>
#> 1 0           -1.53 
#> 2 1            0.504

data %>% 
  pROC::roc(bi, pr)
#> Setting levels: control = 0, case = 1
#> Setting direction: controls < cases
#> 
#> Call:
#> roc.data.frame(data = ., response = bi, predictor = pr)
#> 
#> Data: pr in 20 controls (bi 0) < 20 cases (bi 1).
#> Area under the curve: 0.91

data %>% 
  pROC::roc(bi, pr, direction = '<')
#> Setting levels: control = 0, case = 1
#> 
#> Call:
#> roc.data.frame(data = ., response = bi, predictor = pr, direction = "<")
#> 
#> Data: pr in 20 controls (bi 0) < 20 cases (bi 1).
#> Area under the curve: 0.91

data %>% 
  pROC::roc(bi, pr, direction = '>')
#> Setting levels: control = 0, case = 1
#> 
#> Call:
#> roc.data.frame(data = ., response = bi, predictor = pr, direction = ">")
#> 
#> Data: pr in 20 controls (bi 0) > 20 cases (bi 1).
#> Area under the curve: 0.09

data %>% 
  yardstick::roc_auc(bi, pr)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.910

data %>% 
  yardstick::roc_auc(bi, pr, options = list(direction = '<'))
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary          0.09

data %>% 
  yardstick::roc_auc(bi, pr, options = list(direction = '>'))
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.910
```

<sup>Created on 2020-01-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by topepo** [comment]
`?pROC::roc` has

>  `response`: a factor, numeric or character vector of responses, typically encoded with 0 (controls) and 1 (cases).

So it assumes that the second factor level is the case. When you start `yardstick`, there is the message: 

```
> library(yardstick)
For binary classification, the first factor level is assumed to be the event.
Set the global option `yardstick.event_first` to `FALSE` to change this.
```

Try changing that option and see if they match.

**Comment by mattwarkentin** [comment]
Indeed, setting this option does put the results in agreement. Sorry about the confusion.

**Comment by jcutler79** [comment]
I'm getting a reversed ROC curve from yardstick's roc_curve when compared to pROC, and I have no idea how to fix it. I have yardstick 0.0.7. Specifying a direction option doesn't work (I also noticed it says not to list direction as one of the options in the documentation). Any reason why this is still happening in Feb 2021?

**Comment by topepo** [comment]
@jcutler79 Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please help me help you!

If you've never heard of a reprex before, start by reading "[What is a reprex](https://github.com/tidyverse/reprex#what-is-a-reprex)", and follow the advice further down that page.

**Comment by jcutler79** [comment]
I guess I could start a new issue, if that's better. Here is a reprex:

library(tidyverse)
library(tidymodels)
library(pROC

# Number of observations
sample_size <- 1e3

# Simulate weight of sample_size number of people 
human_weight <- rnorm(sample_size,mean=172,sd=29)
human_weight <- sort(human_weight)

human_weight %>% hist()

rank(human_weight)/sample_size

# Simulate classification of obesity (0 = not_obese; 1 = obese -- see ROC plot below)
random_uniform_obese_or_not <- runif(sample_size) < rank(human_weight)/sample_size 
random_uniform_obese_or_not %>% as.numeric()

plot(human_weight,random_uniform_obese_or_not)

glm_fit <- glm(random_uniform_obese_or_not ~ human_weight,
               family = binomial)
lines(human_weight,glm_fit$fitted.values,col="blue")

# Plot ROC curve using yardstick
glm_fit %>% augment() %>% 
    mutate(obese = if_else(condition=random_uniform_obese_or_not,
                           true = "obese",false = "not_obese")) %>% 
    mutate(obese = as_factor(obese)) %>% 
    
    roc_curve(truth = obese,.fitted) %>% 
    ggplot(aes(x = 1 - specificity, y = sensitivity)) +
    geom_line(color = "#4cc9f0") +
    geom_abline(slope = 1, intercept = 0, size = .4) +
    theme_bw()

# As you can see the ROC curve is below the diagonal (exactly backwards) pROC will correctly put it above the diagonal
glm_fit_data <- glm_fit %>% augment() %>% 
    mutate(obese = if_else(condition=random_uniform_obese_or_not,
                           true = "obese",false = "not_obese")) %>% 
    mutate(obese = as_factor(obese))

par(pty="s")
roc(glm_fit_data$obese,
    glm_fit$fitted.values,
    plot = T,legacy.axes = T)

**Comment by DavisVaughan** [comment]
We definitely recommend opening new issues in the future, linking back to old ones if they are relevant.

For your issue, note that both `glm()` and `pROC::roc()` assume that the _second_ level of your factor is the "event" or "success" by default. yardstick is very clear about the fact that we assume the _first_ level is the "event". You can change this using the `event_level` argument to `roc_curve()`.

``` r
library(tidyverse)
library(tidymodels)
library(pROC)

# Number of observations
sample_size <- 1e3

# Simulate weight of sample_size number of people 
human_weight <- rnorm(sample_size,mean=172,sd=29)
human_weight <- sort(human_weight)

# Simulate classification of obesity (0 = not_obese; 1 = obese -- see ROC plot below)
random_uniform_obese_or_not <- runif(sample_size) < rank(human_weight)/sample_size 

glm_fit <- glm(
  random_uniform_obese_or_not ~ human_weight,
  family = binomial
)

obese_data <- glm_fit %>% 
  augment() %>% 
  mutate(
    obese = if_else(
      condition=random_uniform_obese_or_not,
      true = "obese",
      false = "not_obese"
    )
  ) %>% 
  mutate(obese = as_factor(obese))

# note that the second level is what we consider an "event"
head(obese_data$obese)
#> [1] not_obese not_obese not_obese not_obese not_obese not_obese
#> Levels: not_obese obese

# Tell yardstick to use the 2nd level as the event!
obese_data %>%
  roc_curve(truth = obese, .fitted, event_level = "second") %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_line(color = "#4cc9f0") +
  geom_abline(slope = 1, intercept = 0, size = .4) +
  theme_bw()
```

![](https://i.imgur.com/onrMPIQ.png)

``` r
par(pty="s")
roc(obese_data$obese,
    glm_fit$fitted.values,
    plot = T,legacy.axes = T)
#> Setting levels: control = not_obese, case = obese
#> Setting direction: controls < cases
```

![](https://i.imgur.com/hzd2Gji.png)

**Comment by jcutler79** [comment]
That was so helpful! I was looking around to see if there was an easy fix like that, whether there was an argument like "event_level". Thank you!
