### ISSUE TITLE
A correlation computation is required, but `estimate` is constant and has 0 standard deviation, resulting in a divide by 0 error. `NA` will be returned.

### ISSUE THREAD

**Issue by markhwhiteii** [tidymodels/yardstick#152]
## The problem

When doing grid search in parameter tuning, the following message is returned:

```
A correlation computation is required, but `estimate` is constant and has 0 standard deviation, resulting in a divide by 0 error. `NA` will be returned.
```

There is not much documentation on it; the only mentions of it are in GitHub issues at tidymodels/tune#37 and tidymodels/yardstick#116, I believe.

This is particularly puzzling for me when using `glmnet` for performing LASSO regression.

## Reproducible example

Copy your code to the clipboard and run:

```r
library(tidyverse)
library(tidymodels)
library(glmnet)
n <- 5000
dat <- tibble(
  x1 = rnorm(n),
  x2 = rnorm(n),
  x3 = rnorm(n),
  x4 = rnorm(n),
  x5 = rnorm(n),
  y = x1 + rnorm(n)
)
wf <- workflow()

# split test and train ---------------------------------------------------------
set.seed(1839)
dat_split <- dat %>% 
  initial_split()

dat_train <- training(dat_split)
dat_test <- testing(dat_split)

# preprocessing ----------------------------------------------------------------
dat_train_prep <- recipe(y ~ ., data = dat_train) %>% 
  step_normalize(all_numeric())

wf <- wf %>% 
  add_recipe(dat_train_prep)

# specify model ----------------------------------------------------------------
lasso_spec <- linear_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

wf <- wf %>% 
  add_model(lasso_spec)

# tune for lambda --------------------------------------------------------------
lasso_grid <- tune_grid(
  wf,
  resamples = vfold_cv(dat_train, v = 5),
  grid = grid_regular(penalty(), levels = 50)
)
```

To me, there should not be any places where a singular prediction is being made—that's not how I simulated the data or fit the model. I _think_ this might be happening because `glmnet` is performing `cv.glmnet` under the hood, which fits an intercept-only model first (_I think_), which would give a constant prediction.

Nevertheless, `glmnet` is a popular library, so if this happens in a simple example, I was thinking it might be worth documenting.

**Comment by DavisVaughan** [comment]
@topepo could you provide some more guidance on "when" this occurs? im not sure this one error should become a vignette, but there could be more docs in `?rsq()` about it

**Comment by topepo** [comment]
This can occur when the model predicts a single value for all samples. Two examples could be a regularized model that eliminates all predictors except the intercept and a CART tree that contains no splits.
