### ISSUE TITLE
Store event_first in conf_mat objects

### ISSUE THREAD

**Issue by richierocks** [tidymodels/yardstick#160]
Currently, for binary classification, it seems that whether or not the event is the first factor level can only be set globally, via `options(yardstick.event_first = FALSE)`.

Semantically, it feels as though the event level ought to be a property of the confusion matrix. By storing the event column in the `conf_mat` object, you can more easily work with a mix of response types where sometimes the event is the first level, and other times it is not.

### Minimal, reproducible example:

First, we define two confusion matrices, one where the event isn't the first value, and another where it is.

``` r
library(ggplot2)
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Set the global option `yardstick.event_first` to `FALSE` to change this.
library(withr)

actual_response1 <- rep(c(0, 1, 0, 1), 1:4)
predicted_response1 <- rep(c(0, 0, 1, 1), 1:4)
outcomes1 <- table(predicted_response1, actual_response1)
(confusion1 <- conf_mat(outcomes1))
#>                    actual_response1
#> predicted_response1 0 1
#>                   0 1 2
#>                   1 3 4

actual_response2 <- factor(rep(c("neg", "pos", "neg", "pos"), 1:4), levels = c("pos", "neg"))
predicted_response2 <- factor(rep(c("neg", "neg", "pos", "pos"), 1:4), levels = c("pos", "neg"))
outcomes2 <- table(predicted_response2, actual_response2)
(confusion2 <- conf_mat(outcomes2))
#>                    actual_response2
#> predicted_response2 pos neg
#>                 pos   4   3
#>                 neg   2   1
```

Now if you want to calculate performance metrics, you have to write grim code that specifies a global option.

```r
with_options(
  c(yardstick.event_first = FALSE),
  summary(confusion1)
)
#> # A tibble: 13 x 3
#>    .metric              .estimator .estimate
#>    <chr>                <chr>          <dbl>
#>  1 accuracy             binary        0.5   
#>  2 kap                  binary       -0.0870
#>  3 sens                 binary        0.667 
#>  4 spec                 binary        0.25  
#>  5 ppv                  binary        0.571 
#>  6 npv                  binary        0.333 
#>  7 mcc                  binary       -0.0891
#>  8 j_index              binary       -0.0833
#>  9 bal_accuracy         binary        0.458 
#> 10 detection_prevalence binary        0.7   
#> 11 precision            binary        0.571 
#> 12 recall               binary        0.667 
#> 13 f_meas               binary        0.615

with_options(
  c(yardstick.event_first = TRUE),
  summary(confusion2)
)
#> # A tibble: 13 x 3
#>    .metric              .estimator .estimate
#>    <chr>                <chr>          <dbl>
#>  1 accuracy             binary        0.5   
#>  2 kap                  binary       -0.0870
#>  3 sens                 binary        0.667 
#>  4 spec                 binary        0.25  
#>  5 ppv                  binary        0.571 
#>  6 npv                  binary        0.333 
#>  7 mcc                  binary       -0.0891
#>  8 j_index              binary       -0.0833
#>  9 bal_accuracy         binary        0.458 
#> 10 detection_prevalence binary        0.7   
#> 11 precision            binary        0.571 
#> 12 recall               binary        0.667 
#> 13 f_meas               binary        0.615
```

### Possible changes to `conf_mat()`

I suggest that `conf_mat()` should gain an extra argument, like

```r
first_event = getOption("yardstick.first_event", TRUE)
```

There are several possibilities for how to store the first event information in a `conf_mat` object.

1. Store a logical first event value

In `conf_mat.table()`, the confusion matrix object would be stored as

```r
structure(
    list(table = data, first_event = first_event, dots = list(...)),
    class = "conf_mat"
  )
```

2. Store the column number for the event

Here, you'd calculate the position from the first event argument.

```r
event_col_posn = if(first_event) 1 else 2

structure(
    list(table = data, event_col_posn = event_col_posn, dots = list(...)),
    class = "conf_mat"
  )
```

3. Store the column name for the event

This is similar to the last idea, but stores the name rather than the position.

```r
event_col_posn = if(first_event) 1 else 2
event_col_name = names(dimnames(data))[event_col_posn]

structure(
    list(table = data, event_col_name = event_col_name, dots = list(...)),
    class = "conf_mat"
  )
```

## Ramifications

1. This takes precedence anywhere ` getOption("yardstick.first_event") appears

The global option is currently used in a few places, notably `pos_val()` and `neg_val()`. These functions would need to be modified to receive the value from the confusion matrix.

2. It's not clear how to deal with cases of more than two response categories

I've been concentrating on binary classification. Where there are more than two responses, it isn't totally clear what the behavior ought to be, since there isn't a single "event" category. I don't see any harm in storing the `first_event` value (or whichever you decide on) as `NA`. You probably need to think this through properly though.

**Comment by DavisVaughan** [comment]
I'm going to consider moving towards #163 which would solve this
