### ISSUE TITLE
Desirability functions

### ISSUE THREAD

**Issue by topepo** [tidymodels/yardstick#177]
These are not metrics _per se_ but ways to combine metrics and other statistics. [Here](https://bookdown.org/max/FES/genetic-algorithms.html#coercing-sparsity) is a summary. 

An example application might be that someone wants to optimize their model based on a combination of the ROC and PR curves with different weightings for each. 

There are a few R packages that have them (although [mine](https://cran.r-project.org/web/packages/desirability/vignettes/desirability.pdf) is about as low-tech as packages get).  If you think that the actual desirability functions should be in another package (and imported), that's not a problem. 

@brunaw

**Comment by DavisVaughan** [comment]
@topepo will implement in a separate package
