### ISSUE TITLE
Add precision-recall-gain AUC

### ISSUE THREAD

**Issue by aosavi** [tidymodels/yardstick#185]
The PRG AUC would be a great addition to the already implemented PR AUC:

- https://papers.nips.cc/paper/5867-precision-recall-gain-curves-pr-analysis-done-right.pdf
- https://github.com/meeliskull/prg/tree/master/R_package

**Comment by DavisVaughan** [comment]
At the current moment, we don't see much precedent for this method. I'm going to close this one, but feel free to put in a PR if you really want it!
