### ISSUE TITLE
Confidence intervals do not work for roc_auc

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/yardstick#189]
## The problem

The `ci` argument to `pROC::roc()` doesn't get used when passed to `yardstick::roc_auc()`. Other arguments do work. Any particular reason why this is the case? I couldn't find anything in the documentation about this.

## Reproducible example
``` r
library(magrittr)
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Use the argument `event_level = "second"` to alter this as needed.

mtcars %>% 
  roc_auc(factor(vs), hp)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.937

mtcars %>% 
  roc_auc(factor(vs), hp, options = list(ci = TRUE))
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.937

mtcars %>% 
  roc_auc(factor(vs), hp, options = list(smooth = TRUE))
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.909
```

**Comment by DavisVaughan** [comment]
I don't think we will be able to support this in yardstick. The current API always returns a single value as the metric `.estimate`, but confidence intervals generate 2 values by nature (low/high). For now I would suggest using pROC directly if you need to access that option - in the future we may revisit more general confidence interval computations.
