### ISSUE TITLE
Set autoplot.conf_mat() axis names based on the input conf_mat()$table dimnames 

### ISSUE THREAD

**Issue by CaptureOSM** [tidymodels/yardstick#191]
When plotting a confusion matrix with custom names, 

```
foo <- factor(sample(1:5, 100, replace = T))
bar <- factor(sample(1:5, 100, replace = T))
df <- data.frame(foo, bar)
conf <- yardstick::conf_mat(df, foo, bar, dnn = c("custom", "names"))
conf
    names
custom 1 2 3 4 5
     1 6 7 7 2 3
     2 3 8 3 4 4
     3 2 4 5 5 4
     4 6 3 5 2 3
     5 4 3 4 0 3
```

I noticed that the autoplot method does not take the dimention names from the table. Instead the axis names are hardcoded to "Prediction" and "Truth".

autoplot(conf)
![image](https://user-images.githubusercontent.com/64198462/98125413-be43e800-1eb4-11eb-86f5-cb2a222bbd47.png)

I think it make sense to let the user be able to define custom axis names, either as part of autoplot, or as the title suggests, by letting autoplot take the names defined in the confusion matrix. 

The background is: I am comparing two competing classification outputs, so instead of "Prediction"/"Truth" , something like "Classification foo"/"Classification bar" makes more sense.

**Comment by juliasilge** [comment]
Could do something like `axis_labels <- names(dimnames(cm_zero))` right after this line:

https://github.com/tidymodels/yardstick/blob/5485928e8919a92f0d7beb71436260fe38880e45/R/conf_mat.R#L380

And then use that vector in the `labs`.

In the meantime as a workaround @CaptureOSM the code for making these plots is in that file ⬆️ and you can customize it how you like.

**Comment by DavisVaughan** [comment]
I remember there is some reason we do this, related to https://github.com/tidymodels/yardstick/issues/157 and the fix in https://github.com/tidymodels/yardstick/pull/170. Might be worth revisiting
