### ISSUE TITLE
Plot lines on top of boundary polygon for the gain curve

### ISSUE THREAD

**Issue by eddjberry** [tidymodels/yardstick#192]
Currently the lines for the gain curve are plotted before the boundary polygon. I feel like it looks nicer with the lines on top. Happy to submit a PR if the devs agree :). 

It would just mean changing lines 316 to 336 of [prob-gain_curve.R](https://github.com/tidymodels/yardstick/blob/master/R/prob-gain_curve.R) to 

```
    # boundary poly
    ggplot2::geom_polygon(
      mapping = ggplot2::aes(
        x = !!x,
        y = !!y
      ),
      data = poly_data,
      # fill
      fill = "lightgrey",
      alpha = 0.4
    ) %+%

# gain curve
    ggplot2::geom_line(
      mapping = ggplot2::aes(
        x = !!.percent_tested,
        y = !!.percent_found,
        !!! interact_expr
      ),
      data = object
    ) %+%
```

**Comment by juliasilge** [comment]
Yes, that would definitely be nicer! A PR for this change would be welcome. 🙌
