### ISSUE TITLE
Allow `conf_mat` to display percentages 

### ISSUE THREAD

**Issue by matiasandina** [tidymodels/yardstick#197]
Given a confusion matrix generated by `conf_mat` and displayed using `autoplot`

foo <- factor(sample(LETTERS[1:4], 100, replace = T))
bar <- factor(sample(LETTERS[1:4], 100, replace = T))
df <- data.frame(foo, bar)
conf <- yardstick::conf_mat(df, foo, bar)
ggplot2::autoplot(conf, type="heatmap")

![image](https://user-images.githubusercontent.com/7494967/104959207-b669ef00-599f-11eb-897f-1f53ef2b0cd4.png)

Created on 2021-01-18 by the reprex package (v0.3.0)

Would it be possible to have a confusion matrix with percentages plotted instead of `n` (or `n` and percentage together using something like `glue::glue("{n}\n({percentage})")` to display both of them)? 
If not directly on `conf_mat()` itself, a way to integrate `prop.table()` to `conf$table` and a way to convert back to something `autoplot` can deal with?

**Comment by DavisVaughan** [comment]
I'd encourage looking at the autoplot code and inlining it yourself and tweaking it to do what you'd like.
There are a variety of different ways to compute the percentages that you might want to show, so it isn't completely obvious what the implementation would look like.
