### ISSUE TITLE
Re-licensing yardstick 🤠

### ISSUE THREAD

**Issue by juliasilge** [tidymodels/yardstick#204]
We are systematically re-licensing tidymodels packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all non-RStudio [contributors](https://github.com/tidymodels/yardstick/graphs/contributors). 

@alexhallam, @ClaytonJY, @datenzauberai, @dpastling, @eddjberry, @EmilHvitfeldt, @jyuu, @ledell, @pierreroudier, @riazhedayati, @rorynolan, @rudeboybert, @stephhazlitt, @xrobin, would you permit us to re-license yardstick with the MIT license? If so, please comment "I agree" below.

* [x] [@alexhallam](https://github.com/tidymodels/yardstick/commits?author=alexhallam)  
* [x] [@ClaytonJY](https://github.com/tidymodels/yardstick/commits?author=ClaytonJY)  
* [x] [@datenzauberai](https://github.com/tidymodels/yardstick/commits?author=datenzauberai)  
* [x] [@dpastling](https://github.com/tidymodels/yardstick/commits?author=dpastling)  
* [x] [@eddjberry](https://github.com/tidymodels/yardstick/commits?author=eddjberry)  
* [x] [@EmilHvitfeldt](https://github.com/tidymodels/yardstick/commits?author=EmilHvitfeldt)  
* [x] [@jyuu](https://github.com/tidymodels/yardstick/commits?author=jyuu)  
* [x] [@ledell](https://github.com/tidymodels/yardstick/commits?author=ledell)  
* [x] [@pierreroudier](https://github.com/tidymodels/yardstick/commits?author=pierreroudier)  
* [x] [@riazhedayati](https://github.com/tidymodels/yardstick/commits?author=riazhedayati)  
* [x] [@rorynolan](https://github.com/tidymodels/yardstick/commits?author=rorynolan)  
* [x] [@rudeboybert](https://github.com/tidymodels/yardstick/commits?author=rudeboybert)  
* [x] [@stephhazlitt](https://github.com/tidymodels/yardstick/commits?author=stephhazlitt)  
* [x] [@xrobin](https://github.com/tidymodels/yardstick/commits?author=xrobin)

**Comment by pierreroudier** [comment]
I agree.

**Comment by stephhazlitt** [comment]
I agree.

**Comment by dpastling** [comment]
I agree.

**Comment by xrobin** [comment]
I agree.

**Comment by riazhedayati** [comment]
I agree

**Comment by eddjberry** [comment]
I agree

**Comment by datenzauberai** [comment]
I agree

**Comment by alexhallam** [comment]
I agree

**Comment by jyuu** [comment]
I agree!

**Comment by rorynolan** [comment]
I agree.

**Comment by ledell** [comment]
I agree.
