### ISSUE TITLE
Feature request: Better error messages when regression metrics are using on factors

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/yardstick#209]
If you accidentally use a classification metric when a regression metric should have been used then the error is not great since it bubbles up from `summarize()` with `.estimate` which isn't used by the user.

``` r
library(yardstick)
library(magrittr)

data.frame(truth = 1:100, estimate = 0:99) %>%
  accuracy(truth, estimate)
#> Error: Problem with `summarise()` input `.estimate`.
#> x `truth` should be a factor but a integer was supplied.
#> ℹ Input `.estimate` is `metric_fn(truth = truth, estimate = estimate, na_rm = na_rm)`.

two_class_example %>%
  rmse(truth, predicted)
#> Error: Problem with `summarise()` input `.estimate`.
#> x `truth` should be a numeric but a factor was supplied.
#> ℹ Input `.estimate` is `metric_fn(truth = truth, estimate = predicted, na_rm = na_rm)`.
```

<sup>Created on 2021-03-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
I think that the best place for this to get "fixed" is dplyr, with a better error message for `summarize()`. I discussed internally with the dplyr team and they seem to agree that it could be improved and have a few ideas, so I'll close this one since there is nothing for yardstick to do

**Comment by EmilHvitfeldt** [comment]
What about catching it inside `metric_summarizer()`?

the `metric_nm` can be used to find classes of the function

```r
# For of `metric = "accuracy"
attr(getExportedValue("yardstick", metric_nm), "class")
#> [1] "class_metric" "metric"       "function"
```

**Comment by EmilHvitfeldt** [comment]
If we right here

https://github.com/tidymodels/yardstick/blob/d0512b07dadab1814a796070887134c23c7927f8/R/template.R#L84

put a function to check that might work (quick prototype)

```r
check_var_type <- function(metric_nm, data, truth, estimate) {
  classes <- attr(getExportedValue("yardstick", metric_nm), "class")

  vars <- dplyr::transmute(data, {{truth}}, {{estimate}})
  
  if (classes[1] == "class_metric") {
    factor_ind <- purrr::map_lgl(vars, is.factor)
    
    if (!all(factor_ind)) {
      stop("Both `truth` and `estimate` must be factors")
    }
  }
}
```

but I would understand if we are trying to avoid evaluating `truth` and `estimate` more than once.

**Comment by DavisVaughan** [comment]
I don't have any desire to change the current behavior, but I appreciate the ideas!
