### ISSUE TITLE
Evaluating prediction intervals?

### ISSUE THREAD

**Issue by brshallo** [tidymodels/yardstick#220]
What is guidance on best-practices for evaluating prediction intervals with {tidymodels}? 

Example for measuring coverage on out-of-sample data (the rate at which records are observed to fall within their intervals, i.e. to check whether a 95% prediction interval has 95% coverage):

```{r}
library(tidyverse)
library(tidymodels)

set.seed(1)
split <- initial_split(mpg)
train <- training(split)
test <- testing(split)

lm_mod <- linear_reg() %>% 
  set_engine("lm") %>% 
  fit(hwy ~ displ + cty, data = train)

pred_intervals <- preds_interval <- predict(lm_mod, test, type = "pred_int") %>% 
  bind_cols(test)

coverage <- function(df, truth, lower, upper){
  df %>% 
    mutate(.covered = {{ truth }} >= {{ lower }} & {{ truth }} <= {{ upper }}) %>% 
    summarise(coverage = sum(.covered) / n())
}

pred_intervals %>% 
  coverage(truth = hwy, lower = .pred_lower, upper = .pred_upper)
```
It seems it would be *possible* to set-up a [custom metric](https://yardstick.tidymodels.org/articles/custom-metrics.html) to do this within {yardstick} but would have to use `estimate` argument, e.g. so something like `coverage(truth = hwy, estimate = c(.pred_lower, .pred_upper))`.

But this feels a bit awkward as {yardstick} is meant to evaluate individual or multiple `estimate`(s) -- not intervals (though could perhaps use `yardstick` to measure after calculating `.covered`) or things pertaining to the distributions associated with the estimates.

Hence, am curious how would recommend evaluating prediction intervals (preferably in a way that carries with it the [benefits](https://yardstick.tidymodels.org/articles/custom-metrics.html#custom-metrics) with {yardstick})? Or if an extension package on {yardstick} makes sense...

(This issue stems from Rstudio Community [thread](https://community.rstudio.com/t/prediction-intervals-with-tidymodels-best-practices/82594/21) and Mara's encouragement to open an issue to move discussion to github.)

**Comment by topepo** [comment]
This is out of scope for `yardstick`, mostly because we want to measure performance of specific models (as opposed to evaluating a general method). 

Your own custom method would be best. I would emulate what we do with metrics like `roc_auc()`. In that case, we don't use the `.estimate` argument and pass the quantitative values through using `...`.
