### ISSUE TITLE
Support for `metric_set(list_of_funcs)` or `do.call(metric_set, list)`

### ISSUE THREAD

**Issue by coletl** [tidymodels/yardstick#221]
I really like tidymodels. Thanks for all the hard work.

Would it be possible to create a metric_set object from a list of metric functions? It would be great if `metric_set()` could detect when it's passed a list argument and work automatically like `dplyr::bind_rows()`.

I don't know if it would be any easier to implement, but one alternative is to allow the usual `do.call()`. Right now, using `do.call()` incorrectly fills in the `metric` column, which causes problems for functions like `show_best()`.

``` r
library(tune)
suppressMessages(library(yardstick))

metric_list <- c(f_meas, roc_auc)
mset_from_dots <- metric_set(f_meas, roc_auc)
mset_from_list <- do.call(metric_set, metric_list)

mset_from_dots
#>    metric        class direction
#> 1  f_meas class_metric  maximize
#> 2 roc_auc  prob_metric  maximize

mset_from_list
#>       metric        class direction
#> 1 <clss_mtr> class_metric  maximize
#> 2 <prb_mtrc>  prob_metric  maximize
```

<sup>Created on 2021-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DavisVaughan** [comment]
It is currently not possible to use `metric_set()` like this, and its design unfortunately makes it very difficult to accommodate this. That said, it doesn't seem to happen very often, so I think this is something we will just have to live with.
