### ISSUE TITLE
Using a `metric_set` with `tune_grid()` or `fit_resamples()`

### ISSUE THREAD

**Issue by mattwarkentin** [tidymodels/yardstick#227]
Hi,

Every time I come up against this issue I can never remember how to tackle it: **How do you pass `event_level = "second"` to a `metric_set()` when using `tune_grid()` or `fit_resamples()`?**

When you, as the user, are calling the `metric_set()` directly, you pass it in as an argument, but there doesn't seem to be a way to do it when you aren't the one calling the metric set, such as when it is called internally by `tune_grid()` or `fit_resamples()`. Am I missing something?

``` r
library(tidymodels)

mtcars$vs <- factor(mtcars$vs)

ms <- metric_set(roc_auc)

## Manually pass event_level
ms(mtcars, truth = vs, mpg, event_level = "second")
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.911

## With tune_grid() or fit_resamples()
rs <- bootstraps(mtcars, times = 5)

workflow() %>% 
  add_model(logistic_reg() %>% set_engine("glm")) %>% 
  add_formula(vs ~ mpg) %>% 
  fit_resamples(
    resamples = rs,
    metrics = ms
  )
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 5 x 4
#>   splits          id         .metrics         .notes          
#>   <list>          <chr>      <list>           <list>          
#> 1 <split [32/12]> Bootstrap1 <tibble [1 × 4]> <tibble [0 × 1]>
#> 2 <split [32/10]> Bootstrap2 <tibble [1 × 4]> <tibble [0 × 1]>
#> 3 <split [32/13]> Bootstrap3 <tibble [1 × 4]> <tibble [0 × 1]>
#> 4 <split [32/10]> Bootstrap4 <tibble [1 × 4]> <tibble [0 × 1]>
#> 5 <split [32/16]> Bootstrap5 <tibble [1 × 4]> <tibble [0 × 1]>
```

It *feels* like you should be able to do this when creating the `metric_set`:
```r
ms <- metric_set(roc_auc, event_level = "second")
```
Where unnamed arguments are taken to be metric functions, while named arguments are passed along to the metric functions when they are called as part of the metric set. What do you think?

Similar to `metric_tweak()`, `data`, `truth`, and `estimate` would be protected, but any other optional arguments can be passed as named arguments to `metric_set()`.

**Comment by mattwarkentin** [comment]
This is sort of related to https://github.com/tidymodels/yardstick/issues/180, but the question asks whether `event_level = "second"` is passed to `metric_set()` (to which it is answered "Yes"), but actually it is passed to `metic_set()()`, which caused me some confusion.

**Comment by trilliumtechnical** [comment]
I had the same confusion. This may answer your question:  Setting event level in control_grid or control resamples.

https://tune.tidymodels.org/reference/control_grid.html

**Comment by juliasilge** [comment]
@trilliumtechnical is exactly right that it is in the `control` argument:

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip

mtcars$vs <- factor(mtcars$vs)
ms <- metric_set(roc_auc)
rs <- bootstraps(mtcars, times = 5)

workflow() %>% 
  add_model(logistic_reg() %>% set_engine("glm")) %>% 
  add_formula(vs ~ mpg) %>% 
  fit_resamples(
    resamples = rs,
    metrics = ms,
    control = control_resamples(event_level = "second")
  )
#> # Resampling results
#> # Bootstrap sampling 
#> # A tibble: 5 x 4
#>   splits          id         .metrics         .notes          
#>   <list>          <chr>      <list>           <list>          
#> 1 <split [32/11]> Bootstrap1 <tibble [1 × 4]> <tibble [0 × 1]>
#> 2 <split [32/14]> Bootstrap2 <tibble [1 × 4]> <tibble [0 × 1]>
#> 3 <split [32/11]> Bootstrap3 <tibble [1 × 4]> <tibble [0 × 1]>
#> 4 <split [32/12]> Bootstrap4 <tibble [1 × 4]> <tibble [0 × 1]>
#> 5 <split [32/12]> Bootstrap5 <tibble [1 × 4]> <tibble [0 × 1]>
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
