### ISSUE TITLE
Possible duplication of vignette

### ISSUE THREAD

**Issue by hfrick** [tidymodels/yardstick#236]
I noticed that the yardstick vignette [Custom metric](https://yardstick.tidymodels.org/articles/custom-metrics.html) looks very similar to the [Custom performance metrics](https://www.tidymodels.org/learn/develop/metrics/) article on tidymodels.org . In other packages like parsnip and recipes, the pkgdown site for the individual package links to the article on tidymodels.org instead of keeping the same/similar content in two places. 

Is it intentional that these two articles exist in separate places or should the pkgdown site just link out to tidymodels.org?

**Comment by DavisVaughan** [comment]
Hmm, I would have thought that since this article only used yardstick (as opposed to using many tidymodels packages), it would have just been a yardstick vignette and not on the tidymodels.org site. Creating a new metric is also a somewhat specialized thing that I'd hope most users won't have to do

**Comment by juliasilge** [comment]
Pretty much all the content at [`/learn/develop`](https://www.tidymodels.org/learn/develop/) is a bit specialized and not something most users will have to do, but people who are extending tidymodels (not necessarily in packages but just with internal tooling) have said it is helpful to have the long form instructions about how to make a new recipe, parsnip model, yardstick metric, etc all in one place vs. having to look around at different pkgdown sites. Making custom metrics seems pretty common compared to making, say, a new parsnip model (like for an internal KPI or similar).

It's not the end of the world to maintain two articles but I'd say the tidymodels.org page is probably the higher priority (more people have linked to it or mentioned it); we might consider whether maintaining both is the right call.

**Comment by DavisVaughan** [comment]
Okay that sounds fine. We can:

- Make sure the tidyverse.org post is up to date with any changes that may have happened here
- Delete the yardstick article, instead linking to tidyverse.org
