### ISSUE TITLE
Mean Square Error metric

### ISSUE THREAD

**Issue by fgoerlich** [tidymodels/yardstick#250]
Both, the yardstick vignette [Custom metric](https://yardstick.tidymodels.org/articles/custom-metrics.html) and the [Custom performance metrics](https://www.tidymodels.org/learn/develop/metrics/) article on [tidymodels](https://www.tidymodels.org/) discuss the Mean Square Error metric, `mse()`, but this is **not** a metric implemented in yardstick. This seems a bit curious.

What is implemented is the root mean squared error `rmse()` which is in the same units as the original data, but `mse()` is still wildly used. Wouldn´t be a good idea to implement `mse()` as a verb?

`mse()` is implemented in [modelr](https://modelr.tidyverse.org/reference/model-quality.html) with a different syntaxt that is used in [yardstick](https://yardstick.tidymodels.org/reference/rmse.html).

**Comment by topepo** [comment]
We will probably avoid making `mse()` since it can be computed as the square of the existing function (just to reduce code complexity).
