### ISSUE TITLE
Implementation of new prediction metric for binary outcomes

### ISSUE THREAD

**Issue by ben-domingue** [tidymodels/yardstick#252]
## Feature

We (https://github.com/klintkanopka & https://github.com/crahal) have been working on a novel metric for understanding the quality of predictions for models of binary outcomes. As we argue in the paper, we think this metric has a number of very appealing features (generalizabilty & portability chief amongst them) You can take a look at our idea here: https://osf.io/preprints/socarxiv/gu3ap/

We're interested in beginning to implement the IMV in existing software for model evaluation and the yardstick package is the first thing we thought of. We are posting here prior to a pull request given the instructions about contributing to the tidyverse. Any feedback would be much appreciated!

Ben

**Comment by juliasilge** [comment]
Thank you so much for sharing your work with us @ben-domingue! Given that this is new work/a new method, we think it is out of scope for the kinds of metrics that yardstick will support right now. However, the yardstick framework for metrics is extensible and you yourself can create a custom yardstick metric that will work with all of the tidymodels infrastructure. See:

- https://www.tidymodels.org/learn/develop/metrics/
- https://juliasilge.com/blog/nyc-airbnb/

If you are already releasing an R package with the method for your new metric, you can add a yardstick metric to that package (you will need to put yardstick in `Imports` or `Suggests`). We are very happy to help make sure this all works well, including reviewing your yardstick implementation. Let us know if you would like input in that way!
