### ISSUE TITLE
unexpected behavior: truth and estimate columns not used as defaults in rsq()

### ISSUE THREAD

**Issue by gsverhoeven** [tidymodels/yardstick#255]
## The problem

From the help file to `rsq()` (and more generally `metrics()`), I expected to be able to supply a `data.frame` with columns `truth` and `estimate`, and have `rsq()` use those columns by default. 

I concluded this from the argument description for `data`:

```
data	A data.frame containing the `truth` and `estimate` columns.
```

However, when I do so, it gives me an error. 

## Reproducible example

```r
df <- data.frame(truth = c(1, 2, 3, 4), estimate = c(1, 1, 3, 4))

yardstick::rsq(df)
```

gives me:
```
Error in `validate_not_missing()`:
! `truth` is missing and must be supplied.
Backtrace:
 1. yardstick::rsq(df)
 2. yardstick:::rsq.data.frame(df)
 3. yardstick::metric_summarizer(...)
 4. yardstick:::validate_not_missing(truth, "truth")
 Error in validate_not_missing(truth, "truth") :
```

Am i misreading the helpfile? If so, would it make sense to have `rsq()` look for columns named `truth` and `estimate` as defaults?

**Comment by DavisVaughan** [comment]
It is referring to arguments called `truth` and `estimate`

``` r
df <- data.frame(truth_col = c(1, 2, 3, 4), estimate_col = c(1, 1, 3, 4))

yardstick::rsq(df, truth = truth_col, estimate = estimate_col)
#> # A tibble: 1 × 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 rsq     standard       0.896
```

<sup>Created on 2022-03-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by DavisVaughan** [comment]
```
A data frame containing the columns specified by the `truth` and `estimate` arguments.
```

this is probably more clear

**Comment by gsverhoeven** [comment]
> ```
> A data frame containing the columns specified by the `truth` and `estimate` arguments.
> ```
> 
> this is probably more clear

Yes this would fix the ambiguity in the documentation!
Meanwhile I also discovered `rsq_vec()` . I had two vectors, one with the true values, the other with predictions, and looking for a way to avoid coding 

```
rsq(data.frame(truth_col = c(1, 2, 3, 4), estimate_col = c(1, 1, 3, 4)), truth = truthcol, estimate = estimate_col)
```

I can do this now using:
```
rsq_vec(truth = c(1,2,3,4), estimate = c(1,1,3,4))
```

Thanks for your help!
