### ISSUE TITLE
f_meas cannot be calculated

### ISSUE THREAD

**Issue by sametsoekel** [tidymodels/yardstick#309]
I try to flag `1` as the positive class in this example;

```
library(tidymodels)
library(dplyr)

set.seed(1)


iris2 <- iris %>%
mutate(dummy_class = as.factor(sample(0:1,size = n(),replace =T,prob = c(0.95,0.05)))) 


resampl <- vfold_cv(iris2,v = 3,strata = dummy_class)

metrics <- metric_set(accuracy,f_meas)

mod <- rand_forest() %>%
set_engine('ranger') %>%
set_mode('classification')

ctrl <- control_resamples(verbose = T,event_level = "second")


wf <- workflow() %>%
add_formula(dummy_class ~ Sepal.Width + Petal.Length) %>%
add_model(mod)

fit_rsmpl <- wf %>% fit_resamples(resamples = resampl,metrics = metrics,control = ctrl)
```

it works well when `0` is positive class but in the example above, I get this messages for each fold and f_meas is not calculated;

`While computing binary 'precision()', no predicted events were detected (i.e.'true_positive + false_positive = 0'). Precision is undefined in this case, and'NA' will be returned. Note that 2 true event(s) actually occured for the problematic event level, '1'.
`

other metrics work also.

```
  .metric  .estimator   mean     n std_err .config             
  <chr>    <chr>       <dbl> <int>   <dbl> <chr>               
1 accuracy binary       0.96     3  0.0115 Preprocessor1_Model1
2 f_meas   binary     NaN        0 NA      Preprocessor1_Model1
```

Thanks in advance

**Comment by DavisVaughan** [comment]
I don't think there is any problem here, `f_meas()` is a function of `precision()` and `recall()`, so you have to compute those first to compute `f_meas()`. In some of your resamples, the ranger model predicted all `0`s (i.e. there are no predicted "events" of `1`) which means that precision is undefined, and therefore f-meas is undefined

This just might not be the best metric for this use case
