### ISSUE TITLE
accuracy and ordering of factors -- perhaps linked to issue 162?

### ISSUE THREAD

**Issue by parsifal9** [tidymodels/yardstick#310]
Hi all,

I have a problem with accuracy -- it seems to depend on the ordering of factors.
There is a small reproducible example below.
Apologies for not using "reprex" -- I could not get the clipboard working as expected.

## The problem
1) The problem comes from the example at https://blogs.rstudio.com/ai/posts/2021-02-11-tabnet/
The strange factor levels "1.000000000000000000e+00" are how they appear in the example
2) I can't run the full example so I subsetted the data using 

```r
test1 <- read_csv(
  "HIGGS.csv.gz",
  col_names = c("class", ....),
  col_types = "fdddddddddddddddddddddddddddd",
  skip = 100000 ,
  n_max= 10    
  )
```
which leads to an error. However changing the skip
```r
skip = 100001
```
removes the error

## Reproducible example

```r
library(tidymodels)
p1<-structure(list(class = structure(c(1L, 2L, 1L), levels = c("0.000000000000000000e+00", 
"1.000000000000000000e+00"), class = "factor"), .pred_class = structure(c(2L, 
1L, 2L), levels = c("1.000000000000000000e+00", "0.000000000000000000e+00"
), class = "factor")), row.names = c(NA, -3L), class = c("tbl_df", 
"tbl", "data.frame"))
yardstick::accuracy(p1, class, .pred_class)
yardstick::accuracy(p1, class, .pred_class,event_level = "first")
yardstick::accuracy(p1, class, .pred_class,event_level = "second")

p2<-structure(list(class = structure(c(1L, 2L, 2L), levels = c("1.000000000000000000e+00", 
"0.000000000000000000e+00"), class = "factor"), .pred_class = structure(c(1L, 
2L, 2L), levels = c("1.000000000000000000e+00", "0.000000000000000000e+00"
), class = "factor")), row.names = c(NA, -3L), class = c("tbl_df", 
"tbl", "data.frame"))
yardstick::accuracy(p2, class, .pred_class)
```

p1 gives an error. Setting event_level does not fix it. p2 works as expected.
The error is
```r
Error in `dplyr::summarise()`:
! Problem while computing `.estimate = metric_fn(truth = class, estimate
  = .pred_class, na_rm = na_rm)`.
Caused by error in `binary_checks()`:
! `truth` and `estimate` levels must be equivalent.
`truth`: 0.000000000000000000e+00, 1.000000000000000000e+00
`estimate`: 1.000000000000000000e+00, 0.000000000000000000e+00
Run `rlang::last_error()` to see where the error occurred.
```

**Comment by EmilHvitfeldt** [comment]
You are getting an error because the 10001th value is `0.000000000000000000e+00` and the 10002th value is `1.000000000000000000e+00`.

It appears that `readr::read_cvs()` will set the levels of the factor in the order they appear. This is causing the issue for you as the yardstick functions expect the factor levels to be identical for `truth` and `estimate`. So ideally you want to make sure that your outcome always has the same levels.

Below Is a smaller example.

``` r
library(tidymodels)

p1 <- tibble(
  class = factor(c("a", "b", "a"), levels = c("a", "b")),
  .pred_class = factor(c("a", "b", "a"), levels = c("b", "a"))
)

str(p1)
#> tibble [3 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ class      : Factor w/ 2 levels "a","b": 1 2 1
#>  $ .pred_class: Factor w/ 2 levels "b","a": 2 1 2
```

Notice how the levels above are not the same. This is being expression in the error message below.

```r
accuracy(p1, class, .pred_class)
#> Error in `dplyr::summarise()`:
#> ! Problem while computing `.estimate = metric_fn(truth = class, estimate
#>   = .pred_class, na_rm = na_rm)`.
#> Caused by error in `binary_checks()`:
#> ! `truth` and `estimate` levels must be equivalent.
#> `truth`: a, b
#> `estimate`: b, a
```

If we align the levels to be the same then the functions work

```r
p1$class <- forcats::fct_relevel(p1$class, "b")

str(p1)
#> tibble [3 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ class      : Factor w/ 2 levels "b","a": 2 1 2
#>  $ .pred_class: Factor w/ 2 levels "b","a": 2 1 2

accuracy(p1, class, .pred_class)
#> # A tibble: 1 × 3
#>   .metric  .estimator .estimate
#>   <chr>    <chr>          <dbl>
#> 1 accuracy binary             1
```

<sup>Created on 2022-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by parsifal9** [comment]
Sorry, I did not understand the issues involved. The "forcats::fct_relevel" solution works for the tabnet tutorial.
I apologize for taking up your time. 
Thanks

**Comment by EmilHvitfeldt** [comment]
No need to apologize, we are here to help!
