### ISSUE TITLE
initial survival metrics

### ISSUE THREAD

**Issue by topepo** [tidymodels/yardstick#318]
Let's table the ROC curves for now. There are some methodological issues to work out. 

I think that we should start with concordance for event time outcomes and Brier scores. 

Concordance is pretty straight-forward and there is [already some work on this](https://github.com/tidymodels/yardstick/tree/feature/survival-concordance).

For  Brier scores, I would start by implementing the binary and multi class versions first (for now, let's call that function `brier_class()`). The survival version(s) (say `brier_time()`?) would need an argument for the time to compute the probability. 
There was some previous work here too #18 and #202

Some open questions: 

* How do we include the time setting in the resulting data? 
* If someone specifies multiple time points, how would a user of the tune package specify one of them to optimize on? 
* Some Brier scores need to use weights based on the probability of a data point being censored. There are a lot of ways to do this but a simple KM curve, based on the training set, would do. How would we facilitate that? 
* Brier scores can also be decomposed in a few ways. We should think about doing that in specialized functions (as in #202).

**Comment by EmilHvitfeldt** [comment]
This issue is mostly done now. I'm closing it in favor of https://github.com/tidymodels/yardstick/issues/396, which is used for progress keeping
