### ISSUE TITLE
Pretty conf_mat in Rmarkdown

### ISSUE THREAD

**Issue by ClaytonJY** [tidymodels/yardstick#32]
I love how the `conf_mat` output looks in my console, and would like to make it look similarly nice in an Rmarkdown document. The output seems hard to coerce to a data.frame/tibble to then be `kable`'d, and I had high hopes for `results='asis'` but that squashes the bulk of the content to a single line.

How could we add some support for making these things look nice in knitted output? What's the right path here?

**Comment by topepo** [comment]
Try using the `table` value: 

```r
library(yardstick)

library(dplyr)
data("hpc_cv")

res <- 
  hpc_cv %>%
  filter(Resample == "Fold01") %>%
  conf_mat(obs, pred)

knitr::kable(res$table)
```

This give me:

|   |  VF|  F|  M|  L|
|:--|---:|--:|--:|--:|
|VF | 166| 33|  8|  1|
|F  |  11| 71| 24|  7|
|M  |   0|  3|  5|  3|
|L  |   0|  1|  4| 10|

You can get fancy too:

```r
library(emojifont)
library(knitr)
library(kableExtra)

cells <- c(1, 4)
names(cells) <- c(paste( emoji("point_down"), "Prediction"), "True Values")

kable(res$table, format = "html") %>%
  add_header_above(cells) %>%
  kable_styling(full_width = FALSE)
```

<table class="table" style="width: auto !important; margin-left: auto; margin-right: auto;">
 <thead>
<tr>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="1"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">👇 Prediction</div></th>
<th style="border-bottom:hidden; padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; " colspan="4"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px;">True Values</div></th>
</tr>
  <tr>
   <th style="text-align:left;">   </th>
   <th style="text-align:right;"> VF </th>
   <th style="text-align:right;"> F </th>
   <th style="text-align:right;"> M </th>
   <th style="text-align:right;"> L </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="text-align:left;"> VF </td>
   <td style="text-align:right;"> 166 </td>
   <td style="text-align:right;"> 33 </td>
   <td style="text-align:right;"> 8 </td>
   <td style="text-align:right;"> 1 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> F </td>
   <td style="text-align:right;"> 11 </td>
   <td style="text-align:right;"> 71 </td>
   <td style="text-align:right;"> 24 </td>
   <td style="text-align:right;"> 7 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> M </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 3 </td>
   <td style="text-align:right;"> 5 </td>
   <td style="text-align:right;"> 3 </td>
  </tr>
  <tr>
   <td style="text-align:left;"> L </td>
   <td style="text-align:right;"> 0 </td>
   <td style="text-align:right;"> 1 </td>
   <td style="text-align:right;"> 4 </td>
   <td style="text-align:right;"> 10 </td>
  </tr>
</tbody>
</table>

**Comment by ClaytonJY** [comment]
That does it! Thanks @topepo.
