### ISSUE TITLE
Remove homegrown deprecation functions

### ISSUE THREAD

**Issue by EmilHvitfeldt** [tidymodels/yardstick#323]
> I'm also going to open an issue for us to remove our home-grown deprecation functions.

_Originally posted by @DavisVaughan in https://github.com/tidymodels/yardstick/pull/322#discussion_r982852597_

**Comment by DavisVaughan** [comment]
I think this can probably replace `warn_event_first_deprecated()`

```r
lifecycle::deprecate_warn(
  when = "0.0.7",
  what = I("The global option `yardstick.event_first`"),
  with = I("the metric function argument `event_level`"),
  details = "The global option is being ignored entirely."
)
```

At this point I hope most people have moved off this global option, so I think we can just stop supporting it in the next minor version of yardstick as mentioned here https://github.com/tidymodels/yardstick/issues/173#issuecomment-1234654560

**Comment by DavisVaughan** [comment]
For the roc-curve one you can probably use the standard lifecycle syntax of `what = "roc_curve(options =)"` with an additional line for `details` (and you will need to handle the `what` argument)
https://github.com/tidymodels/yardstick/blob/d56da5e19bf0b5be9adb5e9f2f7e71c80c7a5bea/R/prob-roc_curve.R#L216-L225

And for `conf_mat()` the syntax looks like `what = "conf_mat(...)"`
https://github.com/tidymodels/yardstick/blob/1323a732f28c24d22bbf32c7685b690575d9fa78/R/conf_mat.R#L209-L217

Both of those can also use `deprecate_warn()` I think.

Then you can nuke this file https://github.com/tidymodels/yardstick/blob/main/R/compat-lifecycle.R
