### ISSUE TITLE
Requesting explicit event_level specification

### ISSUE THREAD

**Issue by jmgirard** [tidymodels/yardstick#334]
In addition to letting users specify `event_level` as "first" or "second" for example in `roc_curve()`, I think it would be helpful (and perhaps more intuitive) to let them specify `event_level` explicitly. This would reduce the likelihood of users getting confused about which level is first vs. second.

Setup:
```r
pred <- tibble::tibble(
  id = "train/test split", 
  .pred_A = c(.9, .8, .3, .4), 
  .pred_B = c(.1, .2, .7, .6), 
  .row = c(1, 2, 3, 4), 
  .pred_class = factor(c("A", "A", "B", "B")),
  class = factor(c("A", "A", "B", "B")), 
  .config = "Preprocessor1_Model1"
)
```

Current version:
```r
yardstick::roc_curve(pred, truth = class, .pred_B, event_level = "second")
```

Requested version:
```r
yardstick::roc_curve(pred, truth = class, .pred_B, event_level = "B")
```

**Comment by EmilHvitfeldt** [comment]
Hello @jmgirard 👋 

Thanks for the idea and interest in this project! We will take the idea under advisement

**Comment by DavisVaughan** [comment]
This isn't a bad idea, but I think we are too far down the path of first/second to work on this:

- We'd have to implement it for all metrics, not just `roc_curve()`
- There would be some ambiguity about `event_level = "first"`. Is that a factor level? Or are you requesting the first level to be the event?

I think adding support for that for all metrics is probably more work than we would want to take on at this point in yardstick's lifecycle

**Comment by jmgirard** [comment]
@DavisVaughan If I did the work to implement it for all metrics, would you accept a PR?

**Comment by DavisVaughan** [comment]
No, I don't think so. I really appreciate the offer though. Sometimes we have to turn down good ideas, and this one feels a little too ambiguous to me at the moment. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
