### ISSUE TITLE
Why is error returned if the class is not in the levels?

### ISSUE THREAD

**Issue by kadyb** [tidymodels/yardstick#353]
I'm wondering why it is not possible to calculate metrics of classification performance (e.g. Cohen's kappa or MCC) if the levels in the vectors differ. Currently, an error is returned. I think a fairly common situation is that the classifier has not learned to recognize all classes (i.e. it is underfitted).

```r
library("yardstick")
truth = factor(c("A", "A", "A", "B", "B", "C"))
predicted = factor(c("C", "C", "C", "A", "A", "A"))
kap_vec(truth, predicted)
mcc_vec(truth, predicted)
#> Error in `multiclass_checks()`:
#> ! `truth` and `estimate` levels must be equivalent.
#> `truth`: A, B, C
#> `estimate`: A, C
```

**Comment by EmilHvitfeldt** [comment]
Hello @kadyb 👋 

This is expected to throw an error because the function is unable to tell why truth and predicted have different levels. Hence the requirement that `truth` and `predicted` have the same levels.

Generally, even if a classifier is under-fitted in such a way not to recognize all the classes, it should still know what all the classes are and set the levels according in its prediction. This is the way tidymodels do it, as you can see from this example below

``` r
library(tidymodels)

nn_spec <- nearest_neighbor(neighbors = 20) |>
  set_mode("classification")

sampled_iris <- as_tibble(iris[c(1:55), ])

sampled_iris |>
  count(Species)
#> # A tibble: 2 × 2
#>   Species        n
#>   <fct>      <int>
#> 1 setosa        50
#> 2 versicolor     5

levels(sampled_iris$Species)
#> [1] "setosa"     "versicolor" "virginica"

nn_fit <- fit(nn_spec, Species ~ ., data = sampled_iris)

my_predictions <- predict(nn_fit, new_data = sampled_iris)

my_predictions |>
  count(.pred_class)
#> # A tibble: 1 × 2
#>   .pred_class     n
#>   <fct>       <int>
#> 1 setosa         55

levels(my_predictions$.pred_class)
#> [1] "setosa"     "versicolor" "virginica"
```

Even though, the model doesn't see data points from one of the classes, and completely ignores another class. It still knows the possible values because they are encoded in the levels.

Is this a problem you have run into when using {yardstick}?

**Comment by kadyb** [comment]
Thanks for the answer! In general, in my project I use direct interfaces like `xgb.train()` to train classifiers (without `{tidymodels}`). I use `{yardstick}` to evaluate the performance of the models. It often happens that the classifier is underfitted or there are different classes in the spatial context in the test and training areas. Therefore I can't use the metrics because they return the error of different levels in the vectors. Maybe you could consider changing it to warning?

The situation is similar in `{mlr3measures}`, but in `{Metrics}` it works without error.

```r
library("mlr3measures")
acc(truth, predicted)
#> Error in assert_classif(truth, response = response) :
#>   Assertion on 'levels(truth)' failed: Must be equal to ['A','C'], but is ['A','B','C'].

library("Metrics")
truth = c(1, 1, 1, 2, 2, 3)
predicted = c(3, 3, 3, 1, 1, 1)
ScoreQuadraticWeightedKappa(truth, predicted)
#> [1] -0.8
```

**Comment by EmilHvitfeldt** [comment]
Thank you for your feedback! We really appreciate it!

I'm happy with current implementation. Forcing the levels of `truth` and `estimate` to have the same, seems like a reasonable guardrail. This way we avoid many accidental mistakes. 

I really appreciate the feedback, and hope you'll continue to contribute in the future :smile:

**Comment by kadyb** [comment]
I understand, thanks for your time!
