### ISSUE TITLE
direction=zero not working properly?

### ISSUE THREAD

**Issue by 77makr** [tidymodels/yardstick#366]
I'm having trouble with using e.g. show_best() with metrics like msd or mod, where direction is zero. show_best() or select_best() functions return the model with the lowest msd or mpd, not the model with the msd/mpd closest to zero.
My code is:
```
m1.tune=tune::tune_grid(m1.wflow,resamples=folds1.tune,grid=m1.grid,
                        metrics=metric_set(rmse,rsq,msd,mpe,mae,mape))
show_best(m1.tune,metric="msd",n=20)

```
And the output is:
```
# A tibble: 20 × 9
    mtry trees min_n .metric .estimator   mean     n std_err .config               
   <int> <int> <int> <chr>   <chr>       <dbl> <int>   <dbl> <chr>                 
 1    18   600     2 msd     standard   -0.183    10  0.0685 Preprocessor1_Model020
 2    18   350     2 msd     standard   -0.183    10  0.0680 Preprocessor1_Model018
 3    24   100     2 msd     standard   -0.182    10  0.0696 Preprocessor1_Model021
 4    24   350     2 msd     standard   -0.182    10  0.0676 Preprocessor1_Model023
 5    24   475     2 msd     standard   -0.181    10  0.0669 Preprocessor1_Model024
 6    18   475     2 msd     standard   -0.181    10  0.0682 Preprocessor1_Model019
 7    24   600     2 msd     standard   -0.180    10  0.0690 Preprocessor1_Model025
 8    24   225     2 msd     standard   -0.179    10  0.0681 Preprocessor1_Model022
 9    18   225     2 msd     standard   -0.179    10  0.0677 Preprocessor1_Model017
10    18   100     2 msd     standard   -0.173    10  0.0677 Preprocessor1_Model016
```

Is it a bug or is there any trick I should use to select the best model in terms of msd? You can see that the best model in terms of msd has larger msd (in terms of absolute value) comparing to the model in row 10.
Please help
Maciej

**Comment by EmilHvitfeldt** [comment]
Hello @77makr 👋 

This bug was fixed in {tune} https://github.com/tidymodels/tune/pull/572 on Nov 15, 2022. We haven't had a CRAN release of tune since then so if you want the fix you will have to install the developmental version using `remotes::install_github("tidymodels/tune")`.
