### ISSUE TITLE
Deprecated feature was likely used in the yardstick package.

### ISSUE THREAD

**Issue by nyambea** [tidymodels/yardstick#377]
> twoClassRocCurve <- two_class_example |>
+   roc_curve(truth, Class1)
Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr
1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always
  returns an ungrouped data frame and adjust accordingly.
ℹ The deprecated feature was likely used in the yardstick package.
  Please report the issue at <https://github.com/tidymodels/yardstick/issues>.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.

**Comment by tomwagstaff-opml** [comment]
I also just got this warning running `roc_curve` on a data frame, and was asked to report the issue here. I guess @nyambea got there first!

**Comment by EmilHvitfeldt** [comment]
Hello all! Thank you for reporting this! This has been fixed in the developmental version of {yardstick} in https://github.com/tidymodels/yardstick/pull/356.
