### ISSUE TITLE
`metrics()` default value for `na.rm`

### ISSUE THREAD

**Issue by kevinykuo** [tidymodels/yardstick#40]
This currently defaults to `TRUE`, which means `NA`s in the prediction will be silently ignored. This could be potentially dangerous since the users may think their prediction functions are behaving normally upon seeing reasonable metrics. (Here I'm subjectively claiming that `NA` prediction outputs are "abnormal"...) Are there modeling applications where `NA` predictions are expected? If they're not the norm could we consider displaying a warning if `na.rm` isn't set by the user or changing the default?

**Comment by topepo** [comment]
So I think that it was me that made these defaults and I'm going to keep them that way. Your point is well taken but, if they don't look at their data or know that there are missing values, that's kind of on them.
