### ISSUE TITLE
Potential error in description of `event_level` across several metrics

### ISSUE THREAD

**Issue by bgreenwell** [tidymodels/yardstick#432]
The docs for several metric functions (e.g., `roc_auc`) mention that the default behavior of `event_level` still uses the global option if set:

> A single string. Either "first" or "second" to specify which level of truth to consider as the "event". This argument is only applicable when estimator = "binary". The default uses an internal helper that generally defaults to "first", _**however, if the deprecated global option yardstick.event_first is set, that will be used instead with a warning**_.

However, it appears that the default is always `"first"`?

```r
> packageVersion("yardstick")
[1] ‘1.2.0’

> yardstick:::yardstick_event_level
function () 
{
    opt <- getOption("yardstick.event_first")
    if (!is.null(opt)) {
        lifecycle::deprecate_warn(when = "0.0.7", what = I("The global option `yardstick.event_first`"), 
            with = I("the metric function argument `event_level`"), 
            details = "The global option is being ignored entirely.")
    }
    "first"
}
```

**Comment by EmilHvitfeldt** [comment]
Hello @bgreenwell 👋 

thanks for the keen eye, I'll have that fixed!
