### ISSUE TITLE
metrics.data.frame is using deprecated tidyselect:::vars_select

### ISSUE THREAD

**Issue by rdavis120** [tidymodels/yardstick#447]
I believe that metrics.data.frame is using the deprecated [tidyselect:::vars_select](https://github.com/r-lib/tidyselect/blob/7cc3ea6213838dbb3f9c19e9a8b97cd03f5063a9/R/lifecycle-deprecated.R#L22) function in this line:

```r
  probs <- unname(tidyselect::vars_select(names, ...))
```

**Comment by EmilHvitfeldt** [comment]
Hello @rdavis120! That is a keen eye! That is correct!
