### ISSUE TITLE
Allow logicals at `truth` for binary classification

### ISSUE THREAD

**Issue by vnijs** [tidymodels/yardstick#450]
Why not allow a logical as the `truth` for binary classification metrics (e.g., roc_auc)? The workaround below seems to work in my application but still. Just a thought.

`data[[rvar]] <- factor(data[[rvar]], levels = c("TRUE", "FALSE"))`

**Comment by jxu** [comment]
Most models use a factor for classification, including parsnip `rand_forest` (and probably all other classification models). I would bet most classification models don't predict TRUE or FALSE so it doesn't make sense to allow this.

**Comment by jxu** [comment]
Vaguely related: I had an issue figuring out which level would actually be used by `roc_auc`. https://github.com/tidymodels/tidymodels.org/issues/42

**Comment by EmilHvitfeldt** [comment]
Hello all!

This is similar to https://github.com/tidymodels/yardstick/issues/353. Currently, we are happy with the design where inputs for classification are forced to be factors. By being rigid at this point allows the user to pick up on weirdness in their model

**Comment by vnijs** [comment]
Thanks for your consideration @EmilHvitfeldt
