### ISSUE TITLE
roc_auc_survival appears to be using the wrong weights

### ISSUE THREAD

**Issue by asb2111** [tidymodels/yardstick#495]
I apologize in advance if I am reading the function wrong. 

In the function `roc_curve_survival_impl_one`, the sensitivity appears to be computed as:
$\(\sum{\frac{\Delta I(T\le t)}{n w(t)}}\)^{-1} \sum{\frac{\Delta I(T\le t) I(Pred = 1)}{n w(t)}\)}=\(\sum{\Delta I(T\le t) P(C>t)}\)^{-1} \sum{\Delta I(T\le t) I(Pred = 1)P(C>t)}$,  
where $I(x)$ is an indicator taking value 1 if x is true,  $w(t)$ is the weight for the subject at time t, and Pred is 1 if the subject's predicted value exceeds the threshold value.

For sensitivity, the denominator should be the IPC weighted number of positives, and numerator should be the IPC weighted number positives labeled as positive. But here, instead of applying the weights to the numerator and the denominator, the actual probabilities of remaining uncensored are being applied.

I believe the correction should be changing:
 `multiplier <- delta / (n * data$.weight_censored)`

to:
 `multiplier <- delta * data$.weight_censored`

**Comment by asb2111** [comment]
Similarly, it appears the specificity is not using the weights at all.

**Comment by asb2111** [comment]
A proposed change to the function:
```
roc_curve_survival_impl_one <- function(event_time, delta, data, case_weights) {
  res <- dplyr::tibble(.threshold = sort(unique(c(-Inf, data$.pred_survival, Inf))), decreasing = TRUE)
  
  obs_time_le_time <- event_time <= data$.eval_time
  obs_time_gt_time <- event_time > data$.eval_time
  n <- nrow(data)
  
  sensitivity_denom <- sum(obs_time_le_time * delta * data$.weight_censored * case_weights, na.rm = TRUE)
  specificity_denom <- sum(obs_time_gt_time * data$.weight_censored * case_weights, na.rm = TRUE)
  
  data_df <- data.frame(
    le_time = obs_time_le_time,
    ge_time = obs_time_gt_time,
    delta = data$delta,
    weight_censored = data$.weight_censored,
    case_weights = case_weights
  )
  
  data_split <- vec_split(data_df, data$.pred_survival)
  data_split <- data_split$val[order(data_split$key)]
  
  sensitivity <- vapply(
    data_split,
    function(x) sum(x$le_time * x$delta * x$weight_censored * x$case_weights, na.rm = TRUE),
    FUN.VALUE = numeric(1)
  )
  
  sensitivity <- cumsum(sensitivity)
  sensitivity <- sensitivity / sensitivity_denom
  sensitivity <- dplyr::if_else(sensitivity > 1, 1, sensitivity)
  sensitivity <- dplyr::if_else(sensitivity < 0, 0, sensitivity)
  sensitivity <- c(0, sensitivity, 1)
  res$sensitivity <- sensitivity
  
  specificity <- vapply(
    data_split,
    function(x) sum(x$ge_time * x$weight_censored * x$case_weights, na.rm = TRUE),
    FUN.VALUE = numeric(1)
  )
  specificity <- cumsum(specificity)
  specificity <- specificity / specificity_denom
  specificity <- dplyr::if_else(specificity > 1, 1, specificity)
  specificity <- dplyr::if_else(specificity < 0, 0, specificity)
  specificity <- c(0, specificity, 1)
  specificity <- 1 - specificity
  res$specificity <- specificity

  res
}
```

**Comment by EmilHvitfeldt** [comment]
Hello @asb2111 👋  Thanks for your interest and looking into this issue! 

do you mind referencing a paper/website to support this change?

Thank you!

**Comment by EmilHvitfeldt** [comment]
thank you for the thorough answer! I need to take some time to fully read this through, thank you!
