### ISSUE TITLE
Mutliple AUC plots in one

### ISSUE THREAD

**Issue by jxu** [tidymodels/yardstick#507]
`roc_curve()` has a convenient `autoplot()` function, but it would be nice to have some way of plotting multiple curves on top of each other. 

What I've been doing is adding another `geom_path` to add another curve manually on top.

```
roc_curve(two_class_example, truth, Class1) %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_path() +
  geom_path(aes(x = 1 - specificity, y = sensitivity), new_data, color="blue") + 
  geom_abline(lty = 3) +
  coord_equal() +
  theme_bw()
```

**Comment by EmilHvitfeldt** [comment]
`roc_curve()` works with grouped data set, so if you can combine `roc_curve(two_class_example, truth, Class1)` and `new_data` you can `group_by()` them before passing them into `autoplot()`

``` r
library(tidymodels)

hpc_cv %>%
  group_by(Resample) %>%
  roc_curve(obs, VF:L) %>%
  autoplot()
```

![](https://i.imgur.com/Ak4Ba82.png)

**Comment by EmilHvitfeldt** [comment]
it is, but it is currently being held behind `\dontrun{` because it was taking too long for CRAN https://github.com/tidymodels/yardstick/commit/7dbcc86bb5ad780eec3fd16d600112a474bc3e01

https://yardstick.tidymodels.org/reference/roc_curve.html#ref-examples

**Comment by jxu** [comment]
Oh. For some reason I thought multi-class meant there was some variant of AUC for classifiers with more than 2 classes.
