### ISSUE TITLE
yardstick_event_level removed?

### ISSUE THREAD

**Issue by jxu** [tidymodels/yardstick#510]
https://yardstick.tidymodels.org/reference/metric_set.html

Has yardstick_event_level been removed? It's still referenced in the Class / prob metric set signature. Also in https://yardstick.tidymodels.org/reference/gain_curve.html?search-input=yardstick_event_level#ref-usage and maybe elsewhere.

Is there any way to specify `event_level="second"` for all metrics without tweaking all of them?

**Comment by EmilHvitfeldt** [comment]
As per [{yardstick} 1.2.0](https://yardstick.tidymodels.org/news/index.html#improvements-1-2-0)

> The global option, yardstick.event_first, has been hard deprecated in favor of using explicit argument, event_level. Setting this option will now produce an warning, but won’t have any effect. ([#173](https://github.com/tidymodels/yardstick/issues/173))

What you are seeing `yardstick_event_level()` is a helper function that let us throw a warning whenever people try to use the global option.

> Is there any way to specify event_level="second" for all metrics without tweaking all of them?

Short answer; no.
