### ISSUE TITLE
Could Not Find Function 'roc_curve'

### ISSUE THREAD

**Issue by nmildn** [tidymodels/yardstick#72]
![image](https://user-images.githubusercontent.com/46736742/51226449-76c03500-198a-11e9-9b2a-8d8ee69289d0.png)

**Comment by DavisVaughan** [comment]
What version of yardstick do you have? It sounds like you need to try to update it from Cran

**Comment by nmildn** [comment]
Hi, thanks! Turns out my mirror was outdated.
Though now that I can see this function available from this project,
The same piece of code now returns this error:
Error: all handlers should inherit from `exiting` or `inplace`

How might I resolve this?
