### ISSUE TITLE
F-measure functions fail when precision or recall is undefined

### ISSUE THREAD

**Issue by liam-c-smith** [tidymodels/yardstick#77]
Example:
``` r
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Set the global option `yardstick.event_first` to `FALSE` to change this.

# Prepare data
truth    <- factor(c(rep("a", 10), rep("b", 2)))
estimate <- factor(rep("b", length(truth)), levels(truth))

# Calculate F-measure
f_meas_vec(truth, estimate)
#> Error in if (precision == 0 & rec == 0) {: missing value where TRUE/FALSE needed
f_meas(data.frame(truth, estimate), truth, estimate)
#> Error in summarise_impl(.data, dots): Evaluation error: missing value where TRUE/FALSE needed.
```

<sup>Created on 2019-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I think the issue lies in `yardstick:::f_meas_binary()`. This function checks whether precision and recall are zero so that it can return zero early before the actual F-measure calculation. However, the precision and recall values calculated by `yardstick:::precision_binary()` and `yardstick:::recall_binary()` can return NA if the denominator in the respective calculations is zero. If either returns NA then the logical check in `yardstick:::f_meas_binary()` can't be evaluated and returns an error.

**Comment by DavisVaughan** [comment]
Thanks! Should be fixed now
