### ISSUE TITLE
roc_curve() reversed for me

### ISSUE THREAD

**Issue by igordot** [tidymodels/yardstick#94]
If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [X] Start a new R session
- [X] Install the latest version of of the package: `update.packages(oldPkgs="yardstick", ask=FALSE)`
- [X] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [X] run `sessionInfo()` and add the results to the issue. Even better would be to use the [`sessioninfo`](https://github.com/r-lib/sessioninfo) package's `session_info()`.  

My `roc_curve()` output plot seems to be flipped, at least compared to the `ROCR` output.

```r
library("rpart")
data("kyphosis", package = "rpart")
rp <- rpart(Kyphosis ~ ., data = kyphosis)
library("ROCR")
pred <- prediction(predict(rp, type = "prob")[, 2], kyphosis$Kyphosis)
plot(performance(pred, "tpr", "fpr"))
abline(0, 1, lty = 2)
```
![image](https://user-images.githubusercontent.com/6363505/54330064-b2722680-45ea-11e9-83d5-33107260ccef.png)

```r
library("yardstick")
library("ggplot2")
pred =
  data.frame(
    class1 = predict(rp, type = "prob")[, 1],
    class2 = predict(rp, type = "prob")[, 2],
    predicted = predict(rp, type = "class"),
    truth = kyphosis$Kyphosis
  )
roc_tbl = roc_curve(data = pred, truth, class2)
ggplot(roc_tbl, aes(x = 1 - specificity, y = sensitivity)) +
  geom_abline(linetype = 2, slope = 1, intercept = 0) +
  geom_line(size = 1.2) +
  theme(aspect.ratio = 1)
```
![image](https://user-images.githubusercontent.com/6363505/54330069-b9009e00-45ea-11e9-9d17-c5a1f44bd661.png)

Am I doing something wrong?

`sessionInfo()`:
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.14.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_3.1.0   yardstick_0.0.3 ROCR_1.0-7      gplots_3.0.1    rpart_4.1-13   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0         rstudioapi_0.8     knitr_1.20         magrittr_1.5      
 [5] munsell_0.4.3      tidyselect_0.2.5   colorspace_1.3-2   R6_2.2.2          
 [9] rlang_0.3.1        plyr_1.8.4         dplyr_0.8.0.1      caTools_1.17.1    
[13] tools_3.4.4        grid_3.4.4         gtable_0.2.0       KernSmooth_2.23-15
[17] withr_2.1.2        gtools_3.5.0       lazyeval_0.2.1     yaml_2.1.18       
[21] assertthat_0.2.0   tibble_2.0.1       crayon_1.3.4       purrr_0.2.5       
[25] bitops_1.0-6       glue_1.3.1         labeling_0.3       gdata_2.18.0      
[29] compiler_3.4.4     pillar_1.3.1       scales_0.5.0       pROC_1.14.0       
[33] generics_0.0.2     pkgconfig_2.0.2   
```

**Comment by DavisVaughan** [comment]
You have to be careful about whether these functions use the first / second level of your factor as the "event". By default, `yardstick` chooses the _first_ level of `truth` as the "event" when computing the roc curve. To alter this, use `options(yardstick.event_first = FALSE)` (this is the pop up you get when you load yardstick). 

``` r
library("rpart")
library("yardstick")
#> For binary classification, the first factor level is assumed to be the event.
#> Set the global option `yardstick.event_first` to `FALSE` to change this.
library("ggplot2")

data("kyphosis", package = "rpart")

rp <- rpart(Kyphosis ~ ., data = kyphosis)

pred =
  data.frame(
    class1 = predict(rp, type = "prob")[, 1],
    class2 = predict(rp, type = "prob")[, 2],
    predicted = predict(rp, type = "class"),
    truth = kyphosis$Kyphosis
  )

options(yardstick.event_first = FALSE)

roc_tbl = roc_curve(data = pred, truth, class2)
ggplot(roc_tbl, aes(x = 1 - specificity, y = sensitivity)) +
  geom_abline(linetype = 2, slope = 1, intercept = 0) +
  geom_line(size = 1.2) +
  theme(aspect.ratio = 1)
```

![](https://i.imgur.com/7fyTH1Y.png)

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by igordot** [comment]
Thank you for pointing out `options(yardstick.event_first = FALSE)`. I didn't notice it because there were other events in the same chunk. Adding that solved the problem.

You should consider adding that disclaimer to the function documentation. That setting is already discussed there, but not in the context of binary classification.
